function MetricCard({label,value,caption}){return <div className="col-6 col-md-4 col-xl"><div className="card metric-card h-100 p-3"><div className="text-muted small">{label}</div><div className="metric-value">{value}</div><div className="small text-muted">{caption}</div></div></div>}

function Dashboard({catalog}){
  const weeks=Array.from({length:8},(_,w)=>catalog.reduce((s,p)=>s+(p.usage?.[w]||0),0));
  const max=Math.max(...weeks,1),low=catalog.filter(p=>p.stock<=p.min),value=catalog.reduce((s,p)=>s+p.stock*p.cost,0);
  const top=[...catalog].sort((a,b)=>(b.usage||[]).reduce((x,y)=>x+y,0)-(a.usage||[]).reduce((x,y)=>x+y,0)).slice(0,5);
  return <div><div className="row g-3 mb-3"><MetricCard label="THIS WEEK" value={weeks[7]||0} caption="parts issued"/><MetricCard label="THIS MONTH" value={weeks.slice(4).reduce((a,b)=>a+b,0)} caption="parts issued"/><MetricCard label="AVG / WEEK" value={Math.round(weeks.reduce((a,b)=>a+b,0)/8)||0} caption="parts"/><MetricCard label="STOCK RISK" value={low.length} caption="need attention"/><MetricCard label="INVENTORY VALUE" value={money(value)} caption="on hand"/></div><div className="card metric-card mb-3"><div className="card-body"><h2 className="h5">📈 Parts Used — Last 8 Weeks</h2><div className="chart">{weeks.map((n,i)=><div className="chart-col" key={i}><div className="chart-bar" style={{height:Math.max(5,n/max*180)+'px'}}></div><small className="text-muted mt-1">W{i+1}</small></div>)}</div></div></div><div className="row g-3"><div className="col-lg-6"><div className="card metric-card h-100 p-3"><h2 className="h5">🔥 Most Used Parts</h2>{top.map(p=><div className="border rounded p-3 mb-2" key={p.partNumber}><strong>{p.partNumber}</strong><br/><span className="text-muted">{p.description}</span><span className="badge text-bg-light ms-2">{(p.usage||[]).reduce((a,b)=>a+b,0)} used</span></div>)}</div></div><div className="col-lg-6"><div className="card metric-card h-100 p-3"><h2 className="h5">📦 Stock Health</h2>{low.slice(0,8).map(p=><div className="border rounded p-3 mb-2" key={p.partNumber}><strong>{p.partNumber}</strong> — {p.stock} on hand <span className={p.stock<=0?'stock-out':'stock-low'}>{status(p)}</span></div>)}{!low.length&&<div className="alert alert-success">All stock healthy.</div>}</div></div></div></div>
}

function PartsView({parts,onIssue,onReceive,onDetails}){const [search,setSearch]=React.useState('');const filtered=parts.filter(p=>(p.partNumber+' '+p.description+' '+p.supplier).toLowerCase().includes(search.toLowerCase()));return <div className="card metric-card"><div className="card-body"><div className="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><h2 className="h4 mb-0">Parts Catalog</h2><input className="form-control" style={{maxWidth:340}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search parts, supplier, description"/></div><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Image</th><th>Part</th><th>Description</th><th>Supplier</th><th>Location</th><th>On Hand</th><th>Cost</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.partNumber}><td>{p.image?<img className="part-thumb" src={p.image} onError={e=>e.currentTarget.style.display='none'} alt=""/>:<span className="part-thumb d-inline-block"/>}</td><td><button className="btn btn-link p-0 fw-bold" onClick={()=>onDetails(p)}>{p.partNumber}</button></td><td>{p.description}</td><td>{p.supplier}</td><td>{p.location}</td><td className={p.stock<=0?'stock-out':p.stock<=p.min?'stock-low':'stock-good'}>{p.stock}</td><td>{money(p.cost)}</td><td className="text-nowrap"><button className="btn btn-sm btn-primary me-1" onClick={()=>onIssue(p.partNumber)}>Issue</button><button className="btn btn-sm btn-outline-success" onClick={()=>onReceive(p.partNumber,1)}>Receive</button></td></tr>)}</tbody></table></div></div></div>}

function PartModal({part,onClose,onIssue,onReceive}){if(!part)return null;return <div className="modal d-block" style={{background:'rgba(0,0,0,.45)'}} onClick={onClose}><div className="modal-dialog modal-lg modal-dialog-centered" onClick={e=>e.stopPropagation()}><div className="modal-content"><div className="modal-header"><h5 className="modal-title">{part.partNumber}</h5><button className="btn-close" onClick={onClose}/></div><div className="modal-body"><div className="row g-3"><div className="col-md-4 text-center">{part.image?<img src={part.image} className="img-fluid" style={{maxHeight:220}} onError={e=>e.currentTarget.style.display='none'} alt=""/>:<div className="p-5 bg-light rounded">No image</div>}</div><div className="col-md-8"><p><strong>Description:</strong> {part.description}</p><p><strong>Supplier:</strong> {part.supplier}</p><p><strong>Location:</strong> {part.location}</p><p><strong>On hand:</strong> {part.stock} &nbsp; <strong>Minimum:</strong> {part.min} &nbsp; <strong>Target:</strong> {part.target}</p><p><strong>Unit cost:</strong> {money(part.cost)}</p><div className="d-flex gap-2"><button className="btn btn-primary" onClick={()=>{onIssue(part.partNumber);onClose()}}>Issue 1</button><button className="btn btn-success" onClick={()=>{onReceive(part.partNumber,1);onClose()}}>Receive 1</button></div></div></div></div></div></div></div>}

function ReplenishView({parts,onCreatePO}){const [selected,setSelected]=React.useState({});const toggle=p=>setSelected(s=>({...s,[p.partNumber]:s[p.partNumber]?undefined:Math.max(0,p.target-p.stock)}));const selectedParts=parts.filter(p=>selected[p.partNumber]);const total=selectedParts.reduce((s,p)=>s+(selected[p.partNumber]||0)*p.cost,0);return <div className="card metric-card"><div className="card-body"><div className="d-flex justify-content-between align-items-center mb-3"><h2 className="h4">🛒 Replenishment</h2><span className="badge text-bg-warning">{selectedParts.length} selected</span></div>{parts.length?parts.map(p=><div className="border rounded p-3 mb-2" key={p.partNumber}><div className="d-flex align-items-center gap-3"><input className="form-check-input" type="checkbox" checked={!!selected[p.partNumber]} onChange={()=>toggle(p)}/><div className="flex-grow-1"><strong>{p.partNumber}</strong> — {p.description}<br/><small>On hand {p.stock} • Minimum {p.min} • Target {p.target}</small></div><div><label className="small text-muted">Order qty</label><input className="form-control form-control-sm" style={{width:90}} type="number" min="1" disabled={!selected[p.partNumber]} value={selected[p.partNumber]||Math.max(1,p.target-p.stock)} onChange={e=>setSelected(s=>({...s,[p.partNumber]:Math.max(1,Number(e.target.value)||1)}))}/></div></div></div>):<div className="alert alert-success">No replenishment needed.</div>}{selectedParts.length>0&&<div className="d-flex justify-content-between align-items-center mt-3"><strong>Estimated order: {money(total)}</strong><button className="btn btn-primary" onClick={()=>onCreatePO(selectedParts,selected)}>Create Purchase Order</button></div>}</div></div>}

function TransactionsView({tx}){return <div className="card metric-card"><div className="card-body"><h2 className="h4">Recent Transactions</h2>{tx.slice().reverse().slice(0,50).map((t,i)=><div className="border rounded p-3 mb-2" key={i}><strong>{t.part}</strong> — {t.type} {t.qty}<br/><small className="text-muted">{new Date(t.date).toLocaleString()} • {t.ref}</small></div>)}</div></div>}
function POView({pos}){return <div className="card metric-card"><div className="card-body"><h2 className="h4">📋 Purchase Orders</h2>{pos.length?pos.slice().reverse().map((p,i)=><div className="border rounded p-3 mb-2" key={i}><strong>{p.number}</strong> • {p.status} • {money(p.total)}<br/><small>{p.items.length} line items • {new Date(p.created).toLocaleString()}</small></div>):<div className="alert alert-info">No purchase orders yet.</div>}</div></div>}
function SimpleView({title,children}){return <div className="card metric-card"><div className="card-body"><h2 className="h4">{title}</h2>{children}</div></div>}
function status(p){return p.stock<=0?'OUT OF STOCK':p.stock<=p.min?'LOW STOCK':'HEALTHY'}function money(n){return '$'+Number(n||0).toFixed(2)}
